import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "1.5rem",
        lg: "2rem",
      },
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      screens: {
        xs: "480px",
      },
      minHeight: {
        touch: "44px",
      },
      minWidth: {
        touch: "44px",
      },
      spacing: {
        "safe-top": "env(safe-area-inset-top)",
        "safe-bottom": "env(safe-area-inset-bottom)",
        "safe-left": "env(safe-area-inset-left)",
        "safe-right": "env(safe-area-inset-right)",
      },
      fontFamily: {
        sans:    ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        body:    ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        cia: {
          blue: {
            50:  'hsl(var(--cia-blue-50))',
            100: 'hsl(var(--cia-blue-100))',
            200: 'hsl(var(--cia-blue-200))',
            300: 'hsl(var(--cia-blue-300))',
            400: 'hsl(var(--cia-blue-400))',
            500: 'hsl(var(--cia-blue-500))',
            600: 'hsl(var(--cia-blue-600))',
            700: 'hsl(var(--cia-blue-700))',
            900: 'hsl(var(--cia-blue-900))',
          },
          gold: {
            DEFAULT: 'hsl(var(--cia-gold))',
            50:  'hsl(var(--cia-gold-50))',
            100: 'hsl(var(--cia-gold-100))',
            200: 'hsl(var(--cia-gold-200))',
            300: 'hsl(var(--cia-gold-300))',
            400: 'hsl(var(--cia-gold-400))',
            500: 'hsl(var(--cia-gold-500))',
            600: 'hsl(var(--cia-gold-600))',
          },
          red: {
            50:  'hsl(var(--cia-red-50))',
            100: 'hsl(var(--cia-red-100))',
            300: 'hsl(var(--cia-red-300))',
            500: 'hsl(var(--cia-red-500))',
            600: 'hsl(var(--cia-red-600))',
          },
          navy: "hsl(var(--cia-navy))",
          "navy-light": "hsl(var(--cia-navy-light))",
          sky: "hsl(var(--cia-sky))",
          sand: "hsl(var(--cia-sand))",
          success: "hsl(var(--cia-success))",
          warning: "hsl(var(--cia-warning))",
          xp: "hsl(var(--cia-xp))",
          streak: "hsl(var(--cia-streak))",
          gems: "hsl(var(--cia-gems))",
          bonus: "hsl(var(--cia-bonus))",
        },
        xp:      'hsl(var(--xp-color))',
        streak:  'hsl(var(--streak-color))',
        success: 'hsl(var(--success-color))',
        league: {
          bronze: 'hsl(var(--league-bronze))',
          silver: 'hsl(var(--league-silver))',
          gold:   'hsl(var(--league-gold))',
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
        "3xl": "calc(var(--radius) + 16px)",
        "4xl": "calc(var(--radius) + 24px)",
      },
      boxShadow: {
        sm:      'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md:      'var(--shadow-md)',
        lg:      'var(--shadow-lg)',
        xl:      'var(--shadow-xl)',
        glow:    'var(--shadow-glow)',
        '3d-button-sm':  '0 2px 0 0 hsl(var(--cia-blue-800) / 0.35)',
        '3d-button-md':  '0 3px 0 0 hsl(var(--cia-blue-800) / 0.40)',
        '3d-button-lg':  '0 4px 0 0 hsl(var(--cia-blue-800) / 0.50)',
        '3d-gold-sm':    '0 2px 0 0 hsl(var(--cia-gold-600) / 0.40)',
        '3d-gold-md':    '0 3px 0 0 hsl(var(--cia-gold-600) / 0.50)',
        '3d-gold-lg':    '0 4px 0 0 hsl(var(--cia-gold-600) / 0.55)',
        elevated:        '0 12px 32px -8px rgb(0 0 0 / 0.12), 0 4px 12px -2px rgb(0 0 0 / 0.08)',
        glass:           '0 8px 32px 0 rgb(10 61 98 / 0.15)',
        'glass-strong':  '0 16px 48px -4px rgb(10 61 98 / 0.25), 0 4px 16px -2px rgb(10 61 98 / 0.12)',
      },
      backgroundImage: {
        'gradient-sun':        'linear-gradient(135deg, hsl(var(--cia-gold-200)) 0%, hsl(var(--cia-gold-400)) 50%, hsl(var(--cia-gold-500)) 100%)',
        'gradient-sea':        'linear-gradient(180deg, hsl(var(--cia-blue-300)) 0%, hsl(var(--cia-blue-500)) 50%, hsl(var(--cia-blue-700)) 100%)',
        'gradient-dawn':       'linear-gradient(135deg, hsl(var(--cia-gold-300)) 0%, hsl(var(--cia-blue-500)) 100%)',
        'gradient-sunset':     'linear-gradient(135deg, hsl(var(--cia-red-300)) 0%, hsl(var(--cia-gold-400)) 100%)',
        'gradient-mistral':    'linear-gradient(180deg, hsl(0 0% 100%) 0%, hsl(var(--cia-blue-100)) 100%)',
        'gradient-premium':    'linear-gradient(135deg, hsl(var(--cia-blue-700)) 0%, hsl(var(--cia-blue-900)) 50%, hsl(var(--cia-blue-700)) 100%)',
        'gradient-gold-shine': 'linear-gradient(135deg, hsl(var(--cia-gold-300)) 0%, hsl(var(--cia-gold-500)) 50%, hsl(var(--cia-gold-300)) 100%)',
      },
      transitionTimingFunction: {
        'out-expo':    'var(--ease-out-expo)',
        'out-back':    'var(--ease-out-back)',
        'in-out-soft': 'var(--ease-in-out-soft)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.9)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "bounce-in": {
          "0%": { opacity: "0", transform: "scale(0.3)" },
          "50%": { transform: "scale(1.05)" },
          "70%": { transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "10%, 30%, 50%, 70%, 90%": { transform: "translateX(-4px)" },
          "20%, 40%, 60%, 80%": { transform: "translateX(4px)" },
        },
        "celebrate": {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.2) rotate(5deg)" },
          "100%": { transform: "scale(1) rotate(0)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.8", transform: "scale(1.05)" },
        },
        "progress-fill": {
          from: { width: "0%" },
          to: { width: "var(--progress-width)" },
        },
        "count-up": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        "scale-pop": {
          from: { opacity: "0", transform: "scale(0.92)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "shimmer": {
          from: { backgroundPosition: "-200% 0" },
          to: { backgroundPosition: "200% 0" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 0 0 hsl(var(--cia-gold-400) / 0.4)" },
          "50%": { boxShadow: "0 0 0 12px hsl(var(--cia-gold-400) / 0)" },
        },
        "streak-flame": {
          "0%, 100%": { transform: "rotate(-3deg) scale(1)" },
          "50%": { transform: "rotate(3deg) scale(1.05)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "slide-up": "slide-up 0.5s ease-out forwards",
        "scale-in": "scale-in 0.3s ease-out forwards",
        "bounce-in": "bounce-in 0.6s ease-out forwards",
        "shake": "shake 0.5s ease-out",
        "celebrate": "celebrate 0.5s ease-out",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "progress-fill": "progress-fill 1s ease-out forwards",
        "count-up": "count-up 0.5s ease-out forwards",
        "float": "float 3s ease-in-out infinite",
        "scale-pop": "scale-pop 0.4s var(--ease-out-back)",
        "shimmer": "shimmer 2s ease-in-out infinite",
        "glow-pulse": "glow-pulse 2s ease-out infinite",
        "streak-flame": "streak-flame 1.6s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
